#include "WebInterface.h"
#include "WifiManager.h"
#include <ArduinoJson.h>
#include "Diag.h"

// The HTML file is embedded into the firmware binary at compile time.
// platformio.ini: board_build.embed_txtfiles = data/index.html
// The linker exposes the file content via these two symbols.
extern const uint8_t index_html_start[] asm("_binary_data_index_html_start");
extern const uint8_t index_html_end[]   asm("_binary_data_index_html_end");

extern const uint8_t style_css_start[] asm("_binary_data_style_css_start");
extern const uint8_t style_css_end[]   asm("_binary_data_style_css_end");

extern const uint8_t script_js_start[] asm("_binary_data_script_js_start");
extern const uint8_t script_js_end[]   asm("_binary_data_script_js_end");

/**
 * @brief Construct web server and websocket instances.
 */
WebInterface::WebInterface() : _server(WEB_PORT), _ws("/ws"), _wifiManager(nullptr) {}

/**
 * @brief Initialize WiFi, routes and websocket server.
 */
void WebInterface::begin() {
    if (!_wifiManager) {
        Diag::error("[Web] WifiManager not set, cannot start WiFi");
        return;
    }

    _wifiManager->begin();

    if (!_wifiManager->isConnected()) {
        Diag::error("[Web] WiFi not connected; web interface disabled.");
        return;
    }

    _wifiOk = true;
    char ipBuf[32];
    _wifiManager->getIP(ipBuf, sizeof(ipBuf));
    Diag::infof("[Web] WiFi connected, IP %s", ipBuf);

    // Register the WebSocket event handler using a lambda to forward calls
    // to the private _onWsEvent method (captures `this`).
    _ws.onEvent([this](AsyncWebSocket* s, AsyncWebSocketClient* c,
                        AwsEventType t, void* a, uint8_t* d, size_t l) {
        _onWsEvent(s, c, t, a, d, l);
    });
    _server.addHandler(&_ws);

    // Serve the embedded HTML file on GET /
    _server.on("/", HTTP_GET, [](AsyncWebServerRequest* req) {
        // -1 to ignore the trailing null byte generated by embed_txtfiles
        size_t len = (index_html_end - index_html_start) - 1;
        AsyncWebServerResponse *response = req->beginResponse_P(200, "text/html", index_html_start, len);
        req->send(response);
    });

    _server.on("/style.css", HTTP_GET, [](AsyncWebServerRequest* req) {
        size_t len = (style_css_end - style_css_start) - 1;
        AsyncWebServerResponse *response = req->beginResponse_P(200, "text/css", style_css_start, len);
        req->send(response);
    });

    _server.on("/script.js", HTTP_GET, [](AsyncWebServerRequest* req) {
        size_t len = (script_js_end - script_js_start) - 1;
        AsyncWebServerResponse *response = req->beginResponse_P(200, "application/javascript", script_js_start, len);
        req->send(response);
    });

    _server.on("/recipe.json", HTTP_GET, [this](AsyncWebServerRequest* req) {
        if (!_recipeProvider) {
            req->send(503, "application/json", "{\"error\":\"recipe unavailable\"}");
            return;
        }
        char jsonBuf[2048];
        jsonBuf[0] = '\0';
        _recipeProvider(jsonBuf, sizeof(jsonBuf));
        AsyncWebServerResponse* res = req->beginResponse(200, "application/json", jsonBuf);
        res->addHeader("Content-Disposition", "attachment; filename=pickup-winder-recipe.json");
        req->send(res);
    });

    _server.begin();
    Diag::info("[Web] Server started");
}

/**
 * @brief Serialize and broadcast full machine status to WS clients.
 */
void WebInterface::sendUpdate(const WinderStatus& s) {
    // Skip if WiFi is down or no client is connected.
    if (!_wifiOk || _ws.count() == 0) return;

    // Serialise the full machine state to a compact JSON string.
    // The buffer size (400 bytes) is sized to fit all fields with margin.
    char buf[832];
    snprintf(buf, sizeof(buf),
        "{\"rpm\":%.0f,\"hz\":%u,\"turns\":%ld,\"target\":%ld,\"maxRpm\":%u,"
        "\"running\":%s,\"enabled\":%s,\"startRequested\":%s,\"carriageReady\":%s,\"freerun\":%s,\"cw\":%s,"
        "\"tpp\":%.2f,\"tppCalc\":%.2f,\"tppOfs\":%.2f,\"scatter\":%.2f,"
        "\"pass\":%d,\"activeTpp\":%ld,\"latScale\":%.3f,\"latProgress\":%.3f,\"latPos\":%.3f,\"wStart\":%.3f,\"wEnd\":%.3f,\"wStartTrim\":%.3f,\"wEndTrim\":%.3f,\"eff\":%.2f,"
        "\"gt\":%.2f,\"gb\":%.2f,\"gtp\":%.2f,\"gm\":%.2f,\"gw\":%.4f,"
        "\"latOfs\":%.2f,\"wStyle\":\"%s\",\"seed\":%lu,"
        "\"layerJitter\":%.3f,\"layerSpeed\":%.3f,\"humanTraverse\":%.3f,\"humanSpeed\":%.3f,\"firstPassTraverse\":%.3f,"
            "\"rodageMode\":%s,\"rodagePass\":%d,\"rodagePasses\":%d,\"rodageDist\":%.1f,"
        "\"endPos\":%d,\"endPosTurns\":%d,"
        "\"verifyLow\":%s,\"verifyHigh\":%s,\"state\":\"%s\"}",
        s.rpm, s.speedHz, s.turns, s.targetTurns,
        (unsigned)s.maxRpm,
        s.running      ? "true" : "false",
        s.motorEnabled ? "true" : "false",
        s.startRequested ? "true" : "false",
        s.carriageReady  ? "true" : "false",
        s.freerun      ? "true" : "false",
        s.directionCW  ? "true" : "false",
        s.turnsPerPass, s.turnsPerPassCalc, s.turnsPerPassOffset, s.scatterFactor,
        s.currentPass, s.activeTurnsPerPass, s.activeSpeedScale, s.latProgress,
        s.latPositionMm, s.windingStartMm, s.windingEndMm, s.windingStartTrimMm, s.windingEndTrimMm, s.effectiveWidth_mm,
        s.geomTotal, s.geomBottom, s.geomTop, s.geomMargin, s.geomWire,
        s.latOffset, s.windingStyle, (unsigned long)s.seed,
        s.layerJitterPct, s.layerSpeedPct, s.humanTraversePct, s.humanSpeedPct, s.firstPassTraverseFactor,
        s.rodageMode ? "true" : "false",
        s.rodagePassDone, s.rodagePasses, s.rodageDistMm,
        s.endPos, s.endPosTurns,
        s.verifyLow ? "true" : "false",
        s.verifyHigh ? "true" : "false",
        s.stateName);
    // Broadcast to all connected WebSocket clients.
    _ws.textAll(buf);
}

/** @brief Register command callback used for incoming WS commands. */
void WebInterface::setCommandCallback(CommandCallback cb) {
    _callback = cb;
}

/** @brief Register recipe provider callback used by HTTP export endpoint. */
void WebInterface::setRecipeProvider(RecipeJsonProvider cb) {
    _recipeProvider = cb;
}

/** @brief Broadcast-wired accessor for getIP. */
void WebInterface::getIP(char* buf, size_t len) const {
    if (!_wifiManager || !buf || len == 0) {
        if (buf && len > 0) {
            strncpy(buf, "N/A", len);
            buf[len-1] = '\0';
        }
        return;
    }
    _wifiManager->getIP(buf, len);
}

void WebInterface::setWifiManager(WifiManager* manager) {
    _wifiManager = manager;
}

/**
 * @brief Handle websocket events and forward valid command frames.
 */
void WebInterface::_onWsEvent(AsyncWebSocket* server, AsyncWebSocketClient* client,
                               AwsEventType type, void* arg, uint8_t* data, size_t len) {
    // We only care about data frames; ignore connect/disconnect/error events.
    if (type != WS_EVT_DATA) return;

    AwsFrameInfo* info = (AwsFrameInfo*)arg;
    // Accept only complete, single-frame TEXT messages.
    // Multi-frame or binary messages are ignored for simplicity.
    if (!info->final || info->index != 0 || info->len != len || info->opcode != WS_TEXT) return;

    JsonDocument doc;
    DeserializationError err = deserializeJson(doc, data, len);
    if (err) return;

    const char* cmdIn = doc["cmd"] | "";
    const char* valIn = doc["val"] | "";

    if (_callback && cmdIn && cmdIn[0] != '\0') {
        Diag::infof("[WS-CMD] cmd='%s' val='%s'", cmdIn, valIn);
        _callback(cmdIn, valIn);
    }
}
